/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'G030-T12_v2 - ¸±±¾' 
 * Target:  'G030-T12_v2' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32g0xx.h"

/* Keil::Compiler&ARM Compiler:Event Recorder&DAP@1.5.1 */
#define RTE_Compiler_EventRecorder
#define RTE_Compiler_EventRecorder_DAP
/* Keil::Compiler&ARM Compiler:I/O:STDOUT&EVR@1.2.0 */
#define RTE_Compiler_IO_STDOUT          /* Compiler I/O: STDOUT */
#define RTE_Compiler_IO_STDOUT_EVR      /* Compiler I/O: STDOUT EVR */


#endif /* RTE_COMPONENTS_H */
